import {
  BarChart3,
  Box,
  Coffee,
  ListChecks,
  Moon,
  Settings,
  Users,
} from 'lucide-react'
import type { FeatureCardItem } from '@/types/navigation'

export const featureCards: FeatureCardItem[] = [
  {
    id: 'opening',
    title: '☕ Открыть смену',
    description: 'Старт дня и чек-листы',
    path: '/opening',
    icon: Coffee,
    accentClassName: 'bg-amber-500/15',
    iconClassName: 'text-amber-700 dark:text-amber-300',
  },
  {
    id: 'closing',
    title: '🌙 Закрыть смену',
    description: 'Итоги и закрытие кассы',
    path: '/closing',
    icon: Moon,
    accentClassName: 'bg-indigo-500/15',
    iconClassName: 'text-indigo-700 dark:text-indigo-300',
  },
  {
    id: 'inventory',
    title: '📦 Остатки',
    description: 'Продукты и расходники',
    path: '/inventory',
    icon: Box,
    accentClassName: 'bg-orange-500/15',
    iconClassName: 'text-orange-700 dark:text-orange-300',
  },
  {
    id: 'employees',
    title: '👥 Сотрудники',
    description: 'Команда и роли',
    path: '/employees',
    icon: Users,
    accentClassName: 'bg-emerald-500/15',
    iconClassName: 'text-emerald-700 dark:text-emerald-300',
  },
  {
    id: 'tasks',
    title: '📋 Задачи',
    description: 'Список дел на смену',
    path: '/tasks',
    icon: ListChecks,
    accentClassName: 'bg-sky-500/15',
    iconClassName: 'text-sky-700 dark:text-sky-300',
  },
  {
    id: 'stats',
    title: '📊 Статистика',
    description: 'Показатели и аналитика',
    path: '/stats',
    icon: BarChart3,
    accentClassName: 'bg-violet-500/15',
    iconClassName: 'text-violet-700 dark:text-violet-300',
  },
  {
    id: 'settings',
    title: '⚙ Настройки',
    description: 'Параметры приложения',
    path: '/settings',
    icon: Settings,
    accentClassName: 'bg-stone-500/15',
    iconClassName: 'text-stone-700 dark:text-stone-300',
  },
]
